### ISSUE TITLE
Dropped items not triggering pressure plates

### ISSUE THREAD

**Issue by Velken** [CreativeMD/ItemPhysic#181]
I am playing the UniversIO modpack and whenever I drop items, they don't trigger pressure plates.
I looked online and couldn't find anyone else having same problem as me.

**Comment by CreativeMD** [comment]
Tested it myself and it works just fine. I don't think there is a connection between ItemPhysic and this issue. Also note that not all pressure plates react to items laying on top.

**Comment by Velken** [comment]
I just tested without ItemPhysic and it works as intended
But when dropping from a dropper or an opencrate from botania, they don't trigger
and yes, i am using a wooden pressure plate

**Comment by zachs18** [comment]
@Velken (I'm also playing UniversIO) You probably need to modify your OpenPartiesAndClaims world config to have `Protect Plates From Other: OFF` (default hotkey: `'` > "Player Config Menu" > "My Player Config" > page 3 > "Prot. Plates From Other"), otherwise pressure plates in claimed chunks won't work for automation. (It is indeed unrelated to this mod)
